### PR TITLE
82-snackbar

### PR DESCRIPTION
**Pull request by iamrmrishan**
Added New Feature - SnackBar

### CODE REVIEW

**Comment by iamrmrishan** [comment]
Could you please add "hacktoberfest-accepted" label to the PR? Thank You.

**Comment by cimplesid** [comment]
couldn't merge because  it is already [there](https://github.com/cimplesid/Flutter-for-beginners/tree/master/33-using-snackBars)

**Comment by iamrmrishan** [comment]
Aha sorry.... I didn't saw that there is a SnackBar widget already . let me try some advanced widgets.

**Comment by cimplesid** [comment]
Sure

**Pull request closed without merging**
