### PR TITLE
added example for animated container

### PR DESCRIPTION
**Pull request by hiashutoshsingh**

### CODE REVIEW

**Comment by cimplesid** [comment]
@hiashutoshsingh  thanks for the contribution can you please add the documentation a little bit , single beginner might get into trouble with the code

**Comment by cimplesid** [comment]
else LGTM

**Comment by hiashutoshsingh** [comment]
sure thing, I will do so. @cimplesid

**Comment by hiashutoshsingh** [comment]
@cimplesid Done!

eg- https://dartpad.dev/ad2437c7d1fb0aa1377e8e19d49f4098

**Review by cimplesid — APPROVED** [review]

**Comment by hiashutoshsingh** [comment]
can you also add **_hackoberfest_** tag in your repo it would expand your repo reach and will also motivate others to contribute as well in your repo ?

Thanks

**Comment by cimplesid** [comment]
@hiashutoshsingh  i have added

**Pull request merged**
